import { VausSkin, BallSkin, ThemeScenario } from './types';

export const VAUS_SKINS: VausSkin[] = [
  {
    id: 'vaus_classic',
    name: 'Vaus Original 1986',
    price: 0,
    description: 'La legendaria nave nodriza Vaus con chasis blanco pulido, alerones carmesí y núcleo plateado.',
    bodyColor: '#e2e8f0',
    trimColor: '#dc2626',
    cockpitColor: '#38bdf8',
    glowColor: 'rgba(239, 68, 68, 0.4)',
  },
  {
    id: 'vaus_cyber',
    name: 'Cyber Neon Grid',
    price: 150,
    description: 'Nave de combate digital con luces de neón cian reactivas y alerones ultravioleta.',
    bodyColor: '#090d16',
    trimColor: '#06b6d4',
    cockpitColor: '#a855f7',
    glowColor: 'rgba(6, 182, 212, 0.6)',
  },
  {
    id: 'vaus_gold',
    name: 'Emperador Dorado',
    price: 350,
    description: 'Chasis de oro pulido forjado con aleación estelar y joyas de rubí para maestros de Arkanoid.',
    bodyColor: '#eab308',
    trimColor: '#ca8a04',
    cockpitColor: '#fef08a',
    glowColor: 'rgba(250, 204, 21, 0.6)',
  },
  {
    id: 'vaus_stealth',
    name: 'Titanium Stealth',
    price: 500,
    description: 'Blindaje de fibra de carbono oscura con rayas de advertencia ámbar y propulsor iónico.',
    bodyColor: '#1e293b',
    trimColor: '#f97316',
    cockpitColor: '#fbbf24',
    glowColor: 'rgba(249, 115, 22, 0.5)',
  },
  {
    id: 'vaus_matrix',
    name: 'Matrix Overload',
    price: 750,
    description: 'Estructura codificada en flujo cuántico esmeralda con partículas binarias continuas.',
    bodyColor: '#052e16',
    trimColor: '#22c55e',
    cockpitColor: '#86efac',
    glowColor: 'rgba(34, 197, 94, 0.6)',
  },
];

export const BALL_SKINS: BallSkin[] = [
  {
    id: 'ball_energy',
    name: 'Núcleo de Energía',
    price: 0,
    description: 'Esfera de plasma puro de alta reflectividad con destello blanco arcade.',
    coreColor: '#ffffff',
    glowColor: '#93c5fd',
    trailColor: '#60a5fa',
    trailType: 'simple',
  },
  {
    id: 'ball_fire',
    name: 'Meteoro Solar',
    price: 180,
    description: 'Bola de fuego abrasadora que deja un rastro ardiente de chispas incandescentes.',
    coreColor: '#fef08a',
    glowColor: '#f97316',
    trailColor: '#ef4444',
    trailType: 'fire',
  },
  {
    id: 'ball_plasma',
    name: 'Pulso Iónico',
    price: 320,
    description: 'Descargas de relámpago azul cian con partículas cinéticas de alta velocidad.',
    coreColor: '#e0f2fe',
    glowColor: '#38bdf8',
    trailColor: '#0284c7',
    trailType: 'plasma',
  },
  {
    id: 'ball_rainbow',
    name: 'Espectro Prisma',
    price: 450,
    description: 'Cristal multifacético que cambia de color dinámicamente según la trayectoria.',
    coreColor: '#f43f5e',
    glowColor: '#ec4899',
    trailColor: '#8b5cf6',
    trailType: 'rainbow',
  },
  {
    id: 'ball_pixel',
    name: 'Pixel Retro 8-Bit',
    price: 600,
    description: 'Bloque cúbico pixelado inspirado en los gráficos de microordenador de los años 80.',
    coreColor: '#4ade80',
    glowColor: '#22c55e',
    trailColor: '#16a34a',
    trailType: 'pixel',
  },
];

export const THEME_SCENARIOS: ThemeScenario[] = [
  {
    id: 'theme_arcade',
    name: 'Arcade Gabinete 1986',
    price: 0,
    description: 'Escenario original con paredes metálicas azul cobalto con remaches y cuadrícula clásica.',
    bgDark: '#080c14',
    bgLight: '#1e293b',
    gridColor: 'rgba(56, 189, 248, 0.08)',
    wallColor: '#2563eb',
    wallHighlight: '#60a5fa',
  },
  {
    id: 'theme_space',
    name: 'Espacio Profundo Nébulas',
    price: 220,
    description: 'Fondo de campo de estrellas titilantes y polvo cósmico con marco de grafito violeta.',
    bgDark: '#070510',
    bgLight: '#1f1635',
    gridColor: 'rgba(168, 85, 247, 0.1)',
    wallColor: '#7c3aed',
    wallHighlight: '#c084fc',
  },
  {
    id: 'theme_matrix',
    name: 'Ciber Rejilla Vector',
    price: 380,
    description: 'Ambiente de terminal CRT con malla tridimensional verde fosforescente de alta inmersión.',
    bgDark: '#021008',
    bgLight: '#052e16',
    gridColor: 'rgba(34, 197, 94, 0.12)',
    wallColor: '#15803d',
    wallHighlight: '#4ade80',
  },
  {
    id: 'theme_synthwave',
    name: 'Atardecer Synthwave',
    price: 550,
    description: 'Horizonte retrofuturista de los 80s con rejilla magenta y marco de neón cálido.',
    bgDark: '#13041c',
    bgLight: '#380a42',
    gridColor: 'rgba(236, 72, 153, 0.12)',
    wallColor: '#db2777',
    wallHighlight: '#f472b6',
  },
];
